[tool.poetry]
name = "hass-findmy"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12,<3.13"
homeassistant = "2024.7.4"
findmy = "^0.7.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.2.1"
pre-commit = "^3.6.0"

[tool.ruff]
select = [
    "ALL",
]
ignore = [
    "ANN002", # annotations on `*args`
    "ANN003", # annotations on `**kwargs`
    "ANN101", # annotations on `self`
    "ANN102", # annotations on `cls`

    "D"  # Documentation
]

line-length = 100


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
