[tool.poetry]
name = "hass-findmy"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12,<3.13"
homeassistant = "^2024.9.2"
findmy = "0.7.5"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.5"
pre-commit = "^3.8.0"
pyright = "^1.1.381"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "ALL",
]
ignore = [
    "ANN002", # annotations on `*args`
    "ANN003", # annotations on `**kwargs`
    "ANN101", # annotations on `self`
    "ANN102", # annotations on `cls`

    "D"  # Documentation
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
